apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: movie-verse
spec:
  selector:
    app: app
  type: LoadBalancer
  ports:
  - name: app
    protocol: TCP
    port: 3000
    targetPort: 3000