apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: movie-verse
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /graph
        pathType: Prefix
        backend:
          service:
            name: app
            port:
              number: 3000