apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: movie-verse
spec:
  selector:
    app: neo4j
  type: ClusterIP
  ports:
  - name: neo4j
    protocol: TCP
    port: 7687
    targetPort: 7687
    
---

apiVersion: v1
kind: Service
metadata:
  name: neo4j-dashboard
  namespace: movie-verse
spec:
  selector:
    app: neo4j
  type: NodePort
  ports:
  - name: neo4j-dashboard
    protocol: TCP
    port: 7474
    targetPort: 7474
    nodePort: 30000